spring.application.name=user-service

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/user_service_db
spring.datasource.username=food_user
spring.datasource.password=food_password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration