spring.application.name=payment-service

server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5435/payment_service_db
spring.datasource.username=payment_user
spring.datasource.password=payment_password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

payment.simulation.force-failure=false
