spring.application.name=restaurant-service

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5433/restaurant_service_db
spring.datasource.username=restaurant_user
spring.datasource.password=restaurant_password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
